---

# Author:: Sudarshan (<sudarshan.visham188@gmail.com>)
# Playbook Name:: yum-proxy
# role:: yum_proxy
#
# Copyright 2015, P Sudarshan Rao.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#This role configures yum to use proxy

- name: yum proxy setting
  lineinfile: dest=/etc/yum.conf state=present line="proxy={{ proxy_url }}"


#If proxy server requires username and password. Then uncomment following lines
#
#- lineinfile: dest=/etc/yum.conf state=present line="proxy_username={{ yum_user }}"
#
#- lineinfile: dest=/etc/yum.conf state=present line="proxy_password={{ yum_password }}"
