---

# Author:: Sudarshan (<sudarshan.visham188@gmail.com>)
# Playbook Name:: ambari_deploy
# role:: ambariserver
#
# Copyright 2015, P Sudarshan Rao.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#This installs ambari server and configures
- include_vars: group_vars/main

- name: install ambari server
  yum: name=ambari-server state=present

- name: creating password file
  template: src=roles/ambariserver/templates/password.dat.j2 dest=/etc/ambari-server/conf/password.dat

- name: configure database
  command: /usr/bin/mysql --user={{ ambari_dbuser }} \
           --password={{ ambari_dbpasswd }} \
           --host={{ ambari_dbhost }} \
           -e "SOURCE /var/lib/ambari-server/resources/Ambari-DDL-MySQL-CREATE.sql;" {{ ambari_dbname }}
#  ignore_errors: True

- name: configure ambari
  template: src=roles/ambariserver/templates/ambari.properties.j2 dest=/etc/ambari-server/conf/ambari.properties
  notify:
  - restart ambari server

- name: configure ambari jdbc driver
  command: ambari-server setup --jdbc-db={{ ambari_dbtype }} --jdbc-driver={{ ambari_jdbcdriver }}

- name: start ambari server
  service: name=ambari-server state=started enabled=yes
