---

# Author:: Sudarshan (<sudarshan.visham188@gmail.com>)
# Playbook Name:: kafka-deploy
# role:: kafka
#
# Copyright 2015, P Sudarshan Rao.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- include_vars: group_vars/kafka

- name: checking dependencies
  yum: name=tar state=present

- name: create kafka user
  user: name={{ kafka_user }} state=present

- name: install kafka
  unarchive: src=files/kafka_{{ scala_version }}-{{ kafka_version }}.tar.gz
             dest={{ kafka_dir }}
             creates={{ kafka_home }}
             owner={{ kafka_user }}
             group={{ kafka_user }}


- name: configure kafka
  template: src=roles/kafka/templates/server.properties.j2 dest={{ kafka_home }}/config/server.properties
            owner={{ kafka_user }}
            group={{ kafka_user }}
  notify:
  - restart kafka server

- name: creating kafka log dir
  file: path={{ kafka_logdir }} state=directory
        owner={{ kafka_user }}
        group={{ kafka_user }}

- name: start kafka server
  command: sudo -u {{ kafka_user }} {{ kafka_home }}/bin/kafka-server-start.sh -daemon {{ kafka_home }}/config/server.properties
